base_link: 'base_footprint'

# =====================================================
left_gripper:
    end_effector_name: 'left_gripper'  #ee group name FIXME: moveit group name, not eef name?!?

    #actuated joints in end effector    FIXME
    joints : ['l_gripper_joint']

    #open position
    pregrasp_posture : [0.545]
    pregrasp_time_from_start : 4.0  # TODO ???

    #close position
    grasp_posture : [0.0]
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    # TODO where is the eef here? At the groups parent link?
    # Then this is from there to tool frame
    grasp_pose_to_eef : [-0.18, 0, 0]

    #desired pose from end effector to grasp - [r, p, y]
    grasp_pose_to_eef_rotation : [0, 0, 0]

    end_effector_parent_link: 'l_wrist_roll_link'
# =====================================================
right_gripper:
    end_effector_name: 'right_gripper'  #ee group name

    #actuated joints in end effector
    joints : ['r_gripper_joint']

    #open position
    pregrasp_posture : [0.545]
    pregrasp_time_from_start : 4.0

    #close position
    grasp_posture : [0.0]
    grasp_time_from_start : 4.0

    #desired pose from end effector to grasp - [x,y,z]
    grasp_pose_to_eef : [-0.18, 0, 0]

    #desired pose from end effector to grasp - [r, p, y]
    grasp_pose_to_eef_rotation : [0, 0, 0]

    end_effector_parent_link: 'r_wrist_roll_link'

